gitpod-io/devxconf.org

components/index/developer-productivity.tsx, components/pages/manisfest.tsx
=> Fix typos and ambiguity in the text.

components/index/register-button.tsx, components/index/register-with-email.tsx, lib/google-spreadsheet.ts, lib/render-github-popup.ts, next.config.js, package.json, pages/api/github-oauth.ts, pages/api/register-email.ts, yarn.lock
Relates to #11.
@nisarhassan12 this PR fixes the "Register via email" sign up flow.
=> Move the Google Sheet interactions to the server.

.gitpod.Dockerfile
Improve the size of the base image.
=> Change base image

components/footer.module.css, components/index/hero.module.css, components/text-wrapper.module.css
=> update the colors.

components/about.tsx, pages/index.tsx
=> Fix capitalization of 'DevX'

contents/index.tsx
Fixes gitpod-io/devxconf.org#42
=> Fixes typo

pages/404.module.css, pages/404.tsx
Fixes #23 
This is how it looks:
=> add a custom 404 page.

components/speakers-grid.module.css, components/speakers-grid.tsx
=> remove text + button that are no longer relevant.

contents/index.tsx, contents/schedule-and-stage.tsx
Fixes gitpod-io/devxconf.org#57
=> Updates Speaker details

components/diversity/support.module.css, components/diversity/support.tsx, components/footer.tsx, components/index/consent-note.tsx, components/pages/diversity.module.css, components/pages/diversity.tsx, pages/diversity.tsx
=> Implement DE&I guidelines.

contents/index.tsx, contents/schedule-and-stage.tsx
Fixes gitpod-io/devxconf.org#70
=> schedule title update Jason Warner

lib/render-github-popup.ts
Fixes #20 
This is how it looks:
=>  Update screen for "you have already registered" Fixes #20

components/icons/icon-github.tsx, components/speaker-section.tsx, styles/global.css
=> add hover + focus styles.

contents/index.tsx, contents/schedule-and-stage.tsx
=> update speaker details

contents/index.tsx, contents/schedule-and-stage.tsx
Fixes gitpod-io/devxconf.org#86 #85 #84
=> speaker updates: jason, kyle & inian

contents/expo.tsx
Relates to #89
I missed the question re: sponsor tier in https://github.com/gitpod-io/devxconf.org/issues/89#issuecomment-824240171.
=> Make Console a gold sponsor.

components/enter-stage.tsx, components/index/register-button.tsx, components/index/register-with-email.tsx, components/schedule-sidebar.module.css, components/stage-container.module.css, components/stage-container.tsx, components/stage/enter-stage.module.css, components/stage/enter-stage.tsx, components/talk-card.tsx, lib/cms-api.ts, lib/cms-providers/dato.ts, lib/types.ts, next.config.js, pages/api/stages.ts, pages/stage.tsx, utils/helpers.ts
This PR implements the Stage + the Sign in flow for it. 
This is how the Sign in flow looks:
=> add Stage. 

components/schedule-sidebar.tsx, contents/schedule-and-stage.tsx, pages/stage/[slug].tsx
=> Implement multi-day, multi-stage schedule support

components/schedule.tsx
ATM the schedule look like following this PR makes it look like what it used to be. 
This is how it looks with the changes from the PR:
=> adjust the schedule.

components/schedule.tsx, contents/schedule-and-stage.tsx, lib/types.ts
=> Fix the order of talks in the schedule.

components/schedule-sidebar.tsx
=> Set Thursday as the default day on the schedule selector.

components/index/hero.tsx, components/schedule-sidebar.tsx, components/schedule.tsx, contents/schedule-and-stage.tsx, lib/constants.ts, lib/types.ts
Please merge this before the conference starts again.
=> re remove the sign flow. 

components/layout.module.css, components/layout.tsx, components/schedule-sidebar.module.css, components/schedule-sidebar.tsx, components/schedule.tsx, components/stage-container.module.css, components/stage-container.tsx, components/talk-card.tsx, contents/schedule-and-stage.tsx, lib/constants.ts, lib/types.ts, next.config.js, pages/index.tsx, styles/global.css
Addresses the following as discussed on Slack:
=> Post event updates. 

contents/index.tsx
=> Update Cirpo's details

contents/index.ts
=> Update titles and timings

contents/index.ts
This should be merged before the 2nd day of this year's DevX conf.
=> add streams for day 2.

contents/index.ts
Reverts gitpod-io/devxconf.org#170
=> Revert "add streams for day 2."

contents/index.ts
=> Add Chris to schedule
